// HTube — citate și idei. Traduceri libere în română.
// Format: [text, autor, sursă, categorie]  categorii: mot, dev, biz, soc, san, int (înțelepciune)
window.QUOTES = [
// ── Marcus Aurelius, Meditații (sec. II)
["Obstacolul din calea acțiunii devine acțiunea. Ce stă în drum devine drumul.","Marcus Aurelius","Meditații 5.20","int"],
["Cea mai bună răzbunare e să nu fii ca cel care ți-a greșit.","Marcus Aurelius","Meditații 6.6","int"],
["Nu mai discuta cum ar trebui să fie un om bun. Fii unul.","Marcus Aurelius","Meditații 10.16","dev"],
["Universul e schimbare; viața e ceea ce gândim despre ea.","Marcus Aurelius","Meditații 4.3","int"],
["Fă fiecare lucru ca și cum ar fi ultimul din viața ta.","Marcus Aurelius","Meditații 2.5","mot"],
["Dimineața, când te trezești fără chef, spune-ți: mă ridic ca să fac munca unui om.","Marcus Aurelius","Meditații 5.1","mot"],
["Dacă nu e corect, nu-l face. Dacă nu e adevărat, nu-l spune.","Marcus Aurelius","Meditații 12.17","int"],
["Sufletul ia culoarea gândurilor sale.","Marcus Aurelius","Meditații 5.16","dev"],
["Câștigi mult timp când nu te mai uiți la ce spune, face sau gândește vecinul.","Marcus Aurelius","Meditații 4.18","dev"],
["Nicăieri nu găsești un loc mai liniștit decât în propriul suflet.","Marcus Aurelius","Meditații 4.3","int"],
["Ce nu e bun pentru stup nu e bun nici pentru albină.","Marcus Aurelius","Meditații 6.54","soc"],
["Nu trăi ca și cum ai avea zece mii de ani înainte.","Marcus Aurelius","Meditații 4.17","mot"],
["Nu lucrul din afară te tulbură, ci judecata ta despre el. Pe aceasta o poți șterge chiar acum.","Marcus Aurelius","Meditații 8.47","dev"],
["Fii ca stânca de care se sparg valurile: stă neclintită, iar apa se liniștește în jurul ei.","Marcus Aurelius","Meditații 4.49","mot"],
["Nu aștepta lumea perfectă. Mulțumește-te cu cel mai mic pas înainte.","Marcus Aurelius","Meditații 9.29","dev"],
["Dacă cineva îmi arată că greșesc, mă schimb cu bucurie. Caut adevărul.","Marcus Aurelius","Meditații 6.21","dev"],
["Nu-ți irosi restul vieții gândindu-te la alții, decât dacă e pentru binele comun.","Marcus Aurelius","Meditații 3.4","dev"],
["Caracterul desăvârșit: să trăiești fiecare zi ca pe ultima, fără agitație, fără lene, fără prefăcătorie.","Marcus Aurelius","Meditații 7.69","int"],
["Nu te plânge de viață, nici față de alții, nici față de tine.","Marcus Aurelius","Meditații 8.9","mot"],
["Fă ce trebuie. Restul nu contează: frig sau cald, obosit sau odihnit.","Marcus Aurelius","Meditații 6.2","mot"],
["Ce e propriu omului e să-i iubească și pe cei care greșesc.","Marcus Aurelius","Meditații 7.22","soc"],
["Gândește-te des cât de repede trec și dispar toate lucrurile.","Marcus Aurelius","Meditații 5.23","int"],
["Pierderea nu e altceva decât schimbare.","Marcus Aurelius","Meditații 9.35","int"],
["Mergi mereu pe drumul scurt, iar drumul scurt e cel firesc.","Marcus Aurelius","Meditații 4.51","int"],
["Nu fi nici actor tragic, nici prostituată a părerii altora.","Marcus Aurelius","Meditații 5.28 (liber)","dev"],
// ── Seneca
["Nu avem prea puțin timp, ci pierdem mult din el.","Seneca","Despre scurtimea vieții","mot"],
["Suferim mai des în imaginație decât în realitate.","Seneca","Scrisori 13","dev"],
["Cât trăiești, învață cum să trăiești.","Seneca","Scrisori 76","dev"],
["Dacă nu știi spre ce port navighezi, niciun vânt nu e favorabil.","Seneca","Scrisori 71","biz"],
["Nu îndrăznim pentru că lucrurile sunt grele. Sunt grele pentru că nu îndrăznim.","Seneca","Scrisori 104","mot"],
["Cine e peste tot nu e nicăieri.","Seneca","Scrisori 2","dev"],
["Nu e sărac cel care are puțin, ci cel care vrea mai mult.","Seneca","Scrisori 2","int"],
["Amânarea e cea mai mare risipă a vieții.","Seneca","Despre scurtimea vieții 9","mot"],
["Focul încearcă aurul; greutățile îi încearcă pe oamenii curajoși.","Seneca","Despre providență 5","mot"],
["Ce a fost greu de îndurat e dulce de amintit.","Seneca","Hercules Furens","mot"],
["Începe chiar acum să trăiești.","Seneca","Scrisori 101","mot"],
["Viața e lungă, dacă știi s-o folosești.","Seneca","Despre scurtimea vieții 2","int"],
["Petrece-ți timpul cu cei care te fac mai bun.","Seneca","Scrisori 7","soc"],
["Ce rațiunea nu poate vindeca, adesea vindecă timpul.","Seneca","Agamemnon","int"],
["Nu e liber cel care e sclavul trupului său.","Seneca","Scrisori 92","san"],
["Norocul nu are putere asupra celui care și-a pregătit sufletul.","Seneca","Scrisori (liber)","dev"],
// ── Epictet
["Nu lucrurile ne tulbură, ci părerile noastre despre ele.","Epictet","Manualul 5","dev"],
["Unele lucruri depind de noi, altele nu. Libertatea începe când le deosebești.","Epictet","Manualul 1","dev"],
["Dacă vrei să progresezi, acceptă să pari naiv în privința lucrurilor de afară.","Epictet","Manualul 13","dev"],
["Nu cere ca lucrurile să se întâmple cum vrei. Vrea-le cum se întâmplă și vei trăi liniștit.","Epictet","Manualul 8","int"],
["Nu-ți explica filosofia. Trăiește-o.","Epictet","Manualul 46 (liber)","dev"],
["Nu poți învăța ce crezi că știi deja.","Epictet","Discursuri 2.17","dev"],
["Nimeni nu e liber dacă nu e stăpân pe sine.","Epictet","Fragmente","dev"],
["Greutățile nu fac omul, doar arată din ce e făcut.","Epictet","Discursuri 1.24 (liber)","mot"],
["Până când vei mai amâna să ceri de la tine ce e mai bun?","Epictet","Manualul 51","mot"],
["Când cineva te supără, află că propria ta judecată te-a provocat.","Epictet","Manualul 20","dev"],
["Înțelept e cel care nu se întristează pentru ce nu are, ci se bucură de ce are.","Epictet","Fragmente","int"],
["Avem două urechi și o gură ca să ascultăm de două ori mai mult decât vorbim.","Zenon din Citium","Diogenes Laertius","soc"],
// ── Sun Tzu, Arta războiului
["Cunoaște-ți adversarul și cunoaște-te pe tine, și nu vei fi în pericol în o sută de bătălii.","Sun Tzu","Arta războiului, cap. 3","biz"],
["Arta supremă e să învingi fără luptă.","Sun Tzu","Arta războiului, cap. 3","biz"],
["Învingătorii câștigă întâi, apoi intră în luptă. Învinșii intră în luptă, apoi caută să câștige.","Sun Tzu","Arta războiului, cap. 4","biz"],
["Fii rapid ca vântul, liniștit ca pădurea, aprig ca focul, neclintit ca muntele.","Sun Tzu","Arta războiului, cap. 7","mot"],
["Să nu fii învins depinde de tine. Ocazia de a învinge ți-o dă adversarul.","Sun Tzu","Arta războiului, cap. 4","biz"],
["Apa își croiește drumul după teren. Victoria se croiește după adversar.","Sun Tzu","Arta războiului, cap. 6","biz"],
["Niciun stat n-a câștigat dintr-un război lung.","Sun Tzu","Arta războiului, cap. 2","biz"],
["Atacă unde nu e pregătit. Apari unde nu te așteaptă.","Sun Tzu","Arta războiului, cap. 1","biz"],
["Cine știe când să lupte și când nu, va învinge.","Sun Tzu","Arta războiului, cap. 3","biz"],
["Tratează-ți oamenii ca pe propriii fii și te vor urma oriunde.","Sun Tzu","Arta războiului, cap. 10","soc"],
["Nu te baza pe faptul că adversarul nu va veni. Bazează-te pe pregătirea ta.","Sun Tzu","Arta războiului, cap. 8","biz"],
["Liderul avansează fără să caute faima și se retrage fără să se teamă de rușine.","Sun Tzu","Arta războiului, cap. 10","dev"],
["Liderul trebuie să fie înțelept, sincer, binevoitor, curajos și sever.","Sun Tzu","Arta războiului, cap. 1","dev"],
["Cine e prudent și își așteaptă adversarul nepregătit va învinge.","Sun Tzu","Arta războiului, cap. 3","biz"],
["Viteza este esența războiului.","Sun Tzu","Arta războiului, cap. 11","biz"],
// ── Miyamoto Musashi, Cartea celor cinci inele / Dokkōdō (1645)
["Nu face nimic inutil.","Miyamoto Musashi","Cartea celor cinci inele","dev"],
["Nu regreta ce ai făcut.","Miyamoto Musashi","Dokkōdō","int"],
["O mie de zile de antrenament ca să te formezi, zece mii ca să te șlefuiești.","Miyamoto Musashi","Cartea celor cinci inele","mot"],
["Percepe ce nu se vede cu ochii.","Miyamoto Musashi","Cartea celor cinci inele","dev"],
["Calea se află în antrenament.","Miyamoto Musashi","Cartea celor cinci inele","mot"],
["Nu căuta plăcerea de dragul plăcerii.","Miyamoto Musashi","Dokkōdō","dev"],
["Respectă zeii, dar nu te baza pe ajutorul lor.","Miyamoto Musashi","Dokkōdō","int"],
["Învață toate meseriile; din fiecare vezi calea.","Miyamoto Musashi","Cartea celor cinci inele","biz"],
["Nu te lăsa condus de sentimentul de invidie.","Miyamoto Musashi","Dokkōdō","dev"],
// ── Lao Tzu, Tao Te Ching
["O călătorie de o mie de mile începe cu un singur pas.","Lao Tzu","Tao Te Ching 64","mot"],
["Cine îi cunoaște pe alții e deștept. Cine se cunoaște pe sine e luminat.","Lao Tzu","Tao Te Ching 33","dev"],
["Cine îi învinge pe alții e puternic. Cine se învinge pe sine e cu adevărat puternic.","Lao Tzu","Tao Te Ching 33","mot"],
["Cine știe să se mulțumească e bogat.","Lao Tzu","Tao Te Ching 33","int"],
["Nimic nu e mai moale decât apa, dar nimic nu o întrece în a birui ce e tare.","Lao Tzu","Tao Te Ching 78","int"],
["Cel care știe nu vorbește. Cel care vorbește nu știe.","Lao Tzu","Tao Te Ching 56","int"],
["Lucrurile grele se fac cât sunt ușoare; lucrurile mari, cât sunt mici.","Lao Tzu","Tao Te Ching 63","biz"],
["Cine se laudă nu durează.","Lao Tzu","Tao Te Ching 24","dev"],
// ── Confucius, Analecte
["Ce nu-ți dorești ție, nu face altora.","Confucius","Analecte 15.24","soc"],
["A învăța fără a gândi e muncă pierdută. A gândi fără a învăța e periculos.","Confucius","Analecte 2.15","dev"],
["Când vezi un om vrednic, gândește-te cum să-l ajungi.","Confucius","Analecte 4.17","dev"],
["Omul ales e modest în vorbe și bogat în fapte.","Confucius","Analecte 14.27","dev"],
["Să știi ce știi și să știi ce nu știi: asta e cunoașterea.","Confucius","Analecte 2.17","dev"],
["Adevărata greșeală e să nu-ți corectezi greșelile.","Confucius","Analecte 15.30","dev"],
// ── Filosofi, lideri, sportivi
["Suntem ceea ce facem în mod repetat. Excelența nu e o faptă, ci un obicei.","Will Durant, despre Aristotel","Povestea filosofiei","dev"],
["Nimeni nu intră de două ori în același râu.","Heraclit","Fragmente","int"],
["O viață neexaminată nu merită trăită.","Socrate","Apologia lui Platon","dev"],
["Cine are un «de ce» pentru care să trăiască poate îndura aproape orice «cum».","Friedrich Nietzsche","Amurgul idolilor","mot"],
["Ce nu mă omoară mă face mai puternic.","Friedrich Nietzsche","Amurgul idolilor","mot"],
["Ultima libertate a omului: să-și aleagă atitudinea în orice împrejurare.","Viktor Frankl","Omul în căutarea sensului vieții","dev"],
["Timpul înseamnă bani.","Benjamin Franklin","Sfaturi unui tânăr negustor, 1748","biz"],
["Fă ce poți, cu ce ai, acolo unde ești.","Theodore Roosevelt","Autobiografie","mot"],
["Mânia e o nebunie scurtă.","Horațiu","Epistole","dev"],
["Nu mă tem de cel care a exersat o dată 10.000 de lovituri, ci de cel care a exersat o lovitură de 10.000 de ori.","Bruce Lee","atribuit","mot"],
["Am urât fiecare minut de antrenament, dar mi-am spus: suferă acum și trăiește restul vieții ca un campion.","Muhammad Ali","atribuit","mot"],
["Toată lumea are un plan până ia primul pumn.","Mike Tyson","1987","mot"],
["Stai flămând. Stai nebun.","Steve Jobs","Discurs Stanford, 2005","mot"],
// ── David Goggins
["Cine o să care bărcile?","David Goggins","Can't Hurt Me","mot"],
["Când crezi că nu mai poți, ești abia la 40% din ce poți.","David Goggins","Regula de 40%","mot"],
["Stay hard. Rămâi tare.","David Goggins","","mot"],
["Uită-te în oglindă și spune-ți adevărul despre tine. Acolo începe schimbarea.","David Goggins","Oglinda responsabilității (idee)","mot"],
["Motivația e de rahat. Disciplina te duce mai departe.","David Goggins","idee frecventă","mot"],
["Păstrează un borcan cu biscuiți: lista victoriilor tale grele. Scoate unul când vrei să renunți.","David Goggins","Can't Hurt Me (idee)","mot"],
// ── Dezvoltare personală modernă
["Disciplina e puntea dintre obiective și realizări.","Jim Rohn","","dev"],
["Ești media celor cinci oameni cu care petreci cel mai mult timp.","Jim Rohn","","soc"],
["Nu-ți dori să fie mai ușor. Dorește-ți să fii mai bun.","Jim Rohn","","dev"],
["Motivația nu durează. Nici dușul. De aceea le recomandăm zilnic.","Zig Ziglar","","mot"],
["Ce poate concepe și crede mintea omului, poate și realiza.","Napoleon Hill","De la idee la bani, 1937","mot"],
["Mănâncă broasca: fă prima, dimineața, cea mai grea sarcină.","Brian Tracy","Eat That Frog!","dev"],
["Fiecare minut de planificare economisește zece minute de execuție.","Brian Tracy","Eat That Frog!","biz"],
["Nu cobori la nivelul obiectivelor tale. Cobori la nivelul sistemelor tale.","James Clear","Atomic Habits","dev"],
["Fiecare acțiune e un vot pentru omul care vrei să devii.","James Clear","Atomic Habits","dev"],
["Numără 5-4-3-2-1 și mișcă-te înainte să găsești scuze.","Mel Robbins","The 5 Second Rule","mot"],
// ── Business, bani, persuasiune
["Regula nr. 1: nu pierde bani. Regula nr. 2: nu uita regula nr. 1.","Warren Buffett","","biz"],
["Prețul e ce plătești. Valoarea e ce primești.","Warren Buffett","Scrisoare către acționari, 2008","biz"],
["Durează 20 de ani să construiești o reputație și cinci minute s-o distrugi.","Warren Buffett","","biz"],
["Inversează. Întreabă-te mereu ce ar garanta eșecul și evită asta.","Charlie Munger","","biz"],
["Caută averea, nu banii sau statutul.","Naval Ravikant","How to Get Rich, 2018","biz"],
["Joacă jocuri lungi cu oameni pe termen lung.","Naval Ravikant","How to Get Rich, 2018","biz"],
["Ca să fii interesant, fii interesat de ceilalți.","Dale Carnegie","Cum să-ți faci prieteni (idee)","soc"],
["Oamenii nu cumpără ce faci, ci de ce faci.","Simon Sinek","Start With Why","biz"],
["Nu vinde produsul. Pune întrebări până clientul își spune singur de ce are nevoie.","Jeremy Miner","NEPQ (idee)","biz"],
["Cine pune întrebările controlează conversația.","Jeremy Miner","NEPQ (idee)","biz"],
["Nu negocia niciodată din grabă.","Chris Voss","Never Split the Difference (idee)","biz"],
["„Nu” e începutul negocierii, nu sfârșitul ei.","Chris Voss","Never Split the Difference (idee)","biz"],
// ── Proverbe românești
["Ce ție nu-ți place, altuia nu-i face.","Proverb românesc","","soc"],
["Cine se scoală de dimineață departe ajunge.","Proverb românesc","","mot"],
["Graba strică treaba.","Proverb românesc","","int"],
["Omul sfințește locul.","Proverb românesc","","dev"],
["Ziua bună se cunoaște de dimineață.","Proverb românesc","","mot"],
["Cine nu riscă nu câștigă.","Proverb românesc","","biz"],
["Nu lăsa pe mâine ce poți face azi.","Proverb românesc","","mot"],
["Vorba dulce mult aduce.","Proverb românesc","","soc"],
["Prietenul la nevoie se cunoaște.","Proverb românesc","","soc"],
["Socoteala de acasă nu se potrivește cu cea din târg.","Proverb românesc","","biz"],
["Bate fierul cât e cald.","Proverb românesc","","biz"],
["Cine se aseamănă se adună.","Proverb românesc","","soc"],
// ── Japonia
["Cazi de șapte ori, ridică-te de opt.","Proverb japonez","","mot"],
["Viziunea fără acțiune e un vis. Acțiunea fără viziune e un coșmar.","Proverb japonez","","biz"],
["Chiar și maimuțele cad din copaci.","Proverb japonez","","int"],
["Stai trei ani pe o piatră rece și se va încălzi.","Proverb japonez","","mot"],
["Ce începe cu mânie se termină cu rușine.","Proverb japonez","","dev"],
// ── China
["Cel mai bun moment să plantezi un copac a fost acum 20 de ani. Al doilea cel mai bun e acum.","Proverb chinezesc","","mot"],
["Cine mută un munte începe prin a căra pietre mici.","Proverb chinezesc","","mot"],
["Nu te teme că mergi încet. Teme-te doar că stai pe loc.","Proverb chinezesc","","mot"],
["Profesorii deschid ușa. Intri singur.","Proverb chinezesc","","dev"],
["Când bate vântul schimbării, unii ridică ziduri, alții construiesc mori de vânt.","Proverb chinezesc","","biz"],
["Cerneala cea mai palidă e mai bună decât cea mai bună memorie.","Proverb chinezesc","","dev"],
["Un zâmbet îți va aduce mai mult decât o mie de vorbe.","Proverb chinezesc","","soc"],
// ── Africa
["Dacă vrei să mergi repede, mergi singur. Dacă vrei să mergi departe, mergi împreună.","Proverb african","","soc"],
["Când nu există dușman înăuntru, dușmanii de afară nu te pot răni.","Proverb african","","dev"],
["Când pânzele de păianjen se unesc, pot lega un leu.","Proverb etiopian","","soc"],
["Mâine aparține celor care se pregătesc azi.","Proverb african","","mot"],
["Pădurea nu se face dintr-un singur copac.","Proverb african","","soc"],
// ── Lumea arabă și Persia
["Ai încredere în Dumnezeu, dar leagă-ți cămila.","Proverb arab","","biz"],
["Cine are sănătate are speranță. Cine are speranță are totul.","Proverb arab","","san"],
["Și asta va trece.","Proverb persan","","int"],
["Cine întreabă e prost un minut. Cine nu întreabă rămâne prost toată viața.","Proverb persan","","dev"],
// ── Europa
["Fără muncă, nicio răsplată. (Ohne Fleiß kein Preis)","Proverb german","","mot"],
["Exercițiul îl face pe maestru. (Übung macht den Meister)","Proverb german","","dev"],
["Orice început e greu. (Aller Anfang ist schwer)","Proverb german","","mot"],
["Cine stă pe loc ruginește. (Wer rastet, der rostet)","Proverb german","","san"],
["Prin greutăți, spre stele. (Per aspera ad astra)","Proverb latin","","mot"],
["Norocul îi ajută pe cei curajoși. (Fortes fortuna adiuvat)","Terențiu","Phormio","mot"],
["Grăbește-te încet. (Festina lente)","Proverb latin","","int"],
["Amintește-ți că vei muri. (Memento mori)","Proverb latin","","int"],
["Marea liniștită n-a făcut niciodată un marinar priceput.","Proverb englezesc","","mot"],
["Spune-mi cu cine umbli ca să-ți spun cine ești.","Proverb spaniol","","soc"],
["Cine merge încet merge sănătos și departe.","Proverb italian","","int"],
["Ai încredere, dar verifică.","Proverb rusesc","","biz"],
["Fără muncă nu scoți nici peștele din iaz.","Proverb rusesc","","mot"],
["Bucuria împărțită e dublă. Durerea împărțită e pe jumătate.","Proverb suedez","","soc"],
["O societate devine mare când bătrânii plantează copaci la umbra cărora nu vor sta.","Proverb grecesc","","int"],
// ── Restul lumii
["Nu judeca un om până n-ai mers o lună în mocasinii lui.","Proverb nativ american","","soc"],
["Oricât de departe ai mers pe drumul greșit, întoarce-te.","Proverb turcesc","","dev"],
["Chiar dacă se prăbușește cerul, există o gaură prin care să ieși.","Proverb coreean","","mot"],
["Ce semeni, aceea culegi.","Proverb vechi","","int"],
["Dă-i omului un pește și-l hrănești o zi. Învață-l să pescuiască și-l hrănești o viață.","Proverb","","biz"]
];

// Idei scurte (formulate cu cuvintele mele, pe baza autorilor citați)
window.IDEAS = [
 {c:"dev",who:"Shi Heng Yi",h:"Cele 5 obstacole ale minții",t:"Dorința de plăceri, aversiunea, lenea, neliniștea și îndoiala. Când nu avansezi, întreabă-te care dintre ele te ține pe loc acum. Numindu-l, îi iei din putere.",s:"Învățătură Shaolin / budistă"},
 {c:"dev",who:"Shi Heng Yi",h:"Disciplina ca respect de sine",t:"Nu aștepta să ai chef. Antrenamentul zilnic, mic și constant, construiește un om care se poate baza pe el însuși.",s:"Shi Heng Yi (idee)"},
 {c:"dev",who:"Vadim Zeland",h:"Scade importanța",t:"Cu cât un lucru îți pare mai important, cu atât te încordezi și greșești. Fă tot ce ține de tine, dar ține rezultatul ușor în mână.",s:"Transurfing (idee)"},
 {c:"dev",who:"Vadim Zeland",h:"Pendulele",t:"Știrile, certurile și dramele altora îți cer atenția ca să se hrănească din ea. Nu te lupta cu ele. Doar nu le mai da energie și întoarce-te la scopul tău.",s:"Transurfing (idee)"},
 {c:"dev",who:"Vadim Zeland",h:"Intenția calmă",t:"Nu dorința arzătoare te duce la obiectiv, ci hotărârea liniștită de a avea și de a acționa, fără agitație și fără teamă.",s:"Transurfing (idee)"},
 {c:"dev",who:"Joe Dispenza",h:"Obiceiurile sunt gânduri repetate",t:"Cele mai multe zile seamănă între ele pentru că rulăm aceleași gânduri și emoții. Schimbarea începe când observi tiparul și alegi conștient altă reacție.",s:"Dispenza (idee)"},
 {c:"san",who:"Andrew Huberman",h:"Lumina dimineții",t:"5–10 minute de lumină naturală afară, în prima oră după trezire. Fixează ceasul intern: energie ziua, somn mai bun noaptea.",s:"Huberman Lab"},
 {c:"san",who:"Andrew Huberman",h:"Cafeaua după 90 de minute",t:"Amânarea cafelei cu 60–90 de minute după trezire poate reduce căderea de energie de după-amiază.",s:"Huberman Lab"},
 {c:"san",who:"Andrew Huberman",h:"Dopamina de bază",t:"Recompensele ușoare și dese (telefon, dulciuri) coboară motivația de bază. Efortul și răbdarea o ridică.",s:"Huberman Lab"},
 {c:"san",who:"Andrew Huberman",h:"Respirația care calmează rapid",t:"Două inspirații scurte pe nas, apoi o expirație lungă pe gură. Repetă de 2–3 ori ca să cobori stresul în câteva secunde.",s:"Huberman Lab (physiological sigh)"},
 {c:"san",who:"Peter Attia",h:"Zona 2",t:"Efort la care încă poți vorbi, dar cu greu. Câteva ore pe săptămână construiesc baza de anduranță și sănătatea metabolică.",s:"Outlive"},
 {c:"san",who:"OMS / WHO",h:"Câtă mișcare îți trebuie",t:"150–300 de minute pe săptămână de efort moderat, plus forță de cel puțin 2 ori pe săptămână.",s:"Ghidul OMS, 2020"},
 {c:"san",who:"Somn",h:"Somnul vine primul",t:"Adulții au nevoie de cel puțin 7 ore. Fără somn, antrenamentul, dieta și concentrarea dau rezultate slabe.",s:"AASM / CDC"},
 {c:"mot",who:"David Goggins",h:"Regula de 40%",t:"Când mintea spune „gata”, corpul are încă mult în rezervă. Data viitoare când vrei să renunți, mai fă o repetare, un minut, un pas.",s:"Can't Hurt Me"},
 {c:"mot",who:"David Goggins",h:"Călește-ți mintea",t:"Fă în fiecare zi ceva ce nu-ți place. Disconfortul repetat te face mai greu de oprit.",s:"Can't Hurt Me (idee)"},
 {c:"biz",who:"Alex Hormozi",h:"Ecuația valorii",t:"Valoarea crește cu rezultatul dorit și certitudinea lui. Scade cu timpul de așteptare și efortul cerut clientului. Lucrează pe toate patru.",s:"$100M Offers"},
 {c:"biz",who:"Alex Hormozi",h:"Volumul bate norocul",t:"Majoritatea afacerilor mici nu au o problemă de strategie, ci de volum: prea puține oferte, prea puține contacte pe zi.",s:"$100M Leads (idee)"},
 {c:"biz",who:"Alex Hormozi",h:"Rezolvă problema următoare",t:"După ce clientul cumpără, apare o nouă problemă. Ofertele bune o rezolvă înainte s-o simtă el.",s:"Hormozi (idee)"},
 {c:"biz",who:"Jeremy Miner",h:"Întrebări în loc de argumente",t:"Oamenii cred ce spun ei, nu ce le spui tu. Pune întrebări care îi fac să-și descrie singuri problema și costul ei.",s:"NEPQ"},
 {c:"biz",who:"Jeremy Miner",h:"Ton detașat",t:"Când pari că ai nevoie de vânzare, clientul se retrage. Vorbește calm, curios, fără presiune.",s:"NEPQ (idee)"},
 {c:"biz",who:"Chris Voss",h:"Oglindirea",t:"Repetă ultimele 1–3 cuvinte ale celuilalt, ca întrebare. Continuă să vorbească și îți dă informații.",s:"Never Split the Difference"},
 {c:"biz",who:"Chris Voss",h:"Etichetarea",t:"„Pare că îți faci griji pentru preț.” Numind emoția, o dezamorsezi și omul se simte înțeles.",s:"Never Split the Difference"},
 {c:"biz",who:"Robert Cialdini",h:"Reciprocitatea",t:"Oamenii simt nevoia să întoarcă un gest. Dă primul ceva util, fără condiții.",s:"Influence"},
 {c:"biz",who:"Robert Cialdini",h:"Dovada socială",t:"Când nu sunt siguri, oamenii se uită la ce fac alții ca ei. Arată recenzii și clienți reali.",s:"Influence"},
 {c:"biz",who:"Paul Graham",h:"Fă lucruri care nu se scalează",t:"La început câștigi clienții unul câte unul, cu grijă personală. Firmele mari nu pot copia asta.",s:"Eseu, 2013"},
 {c:"biz",who:"Pareto",h:"Regula 80/20",t:"20% din clienți, produse sau sarcini aduc 80% din rezultat. Găsește-i și pune-ți energia acolo.",s:"Principiul Pareto"},
 {c:"soc",who:"Dale Carnegie",h:"Numele omului",t:"Numele unei persoane e pentru ea cel mai frumos sunet. Reține-l și folosește-l.",s:"Cum să-ți faci prieteni"},
 {c:"soc",who:"Dale Carnegie",h:"Vorbește despre interesele lui",t:"Cel mai sigur drum spre inima cuiva: vorbește despre ce îl interesează pe el.",s:"Cum să-ți faci prieteni"},
 {c:"dev",who:"Cal Newport",h:"Munca profundă",t:"60–90 de minute fără telefon pentru cea mai grea sarcină a zilei. Atenția fragmentată costă mai mult decât crezi.",s:"Deep Work"},
 {c:"dev",who:"James Clear",h:"Regula de 2 minute",t:"Orice obicei nou începe cu o versiune de 2 minute: o pagină citită, o flotare, încălțat adidașii.",s:"Atomic Habits"},
 {c:"dev",who:"Jocko Willink",h:"Responsabilitate totală",t:"Când ceva merge prost, întreabă întâi ce puteai face tu diferit. Cine își asumă tot, controlează mai mult.",s:"Extreme Ownership"},
 {c:"dev",who:"Stoicism",h:"Exercițiul de seară",t:"Seara, întreabă-te: ce am făcut bine, unde am greșit, ce fac mâine diferit. Seneca făcea asta zilnic.",s:"Seneca, Despre mânie 3.36"},
 {c:"dev",who:"Stoicism",h:"Premeditatio malorum",t:"Imaginează-ți dimineața ce poate merge prost. Nu ca să te sperii, ci ca să fii pregătit și calm când se întâmplă.",s:"Practică stoică"}
];
